# Generated by Django 6.0.7 on 2026-07-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple_id', models.CharField(max_length=10, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('open_time', models.CharField(max_length=10)),
                ('close_time', models.CharField(max_length=10)),
                ('visit_time', models.FloatField(help_text='Visit time in hours')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['temple_id'],
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance in km')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads_to', to='guide.temple')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads_from', to='guide.temple')),
            ],
            options={
                'unique_together': {('source', 'destination')},
            },
        ),
    ]
